### PR TITLE
Add Pylint configuration

### PR DESCRIPTION
**Pull request by philipbl**
- Add pylint configuration so we are all working with the same config. Feel free to make changes and submit a PR.

- I also cleaned up `main.py` and most of the runner module.

### CODE REVIEW

**Review by christopolise — COMMENTED** [review]
Seems good to me! It hasn't passed the RPi check, so I am not sure if we should hold off until it has passed or not

**Review by apal6981 — APPROVED** [review]
Looks good

**Comment by christopolise** [comment]
Got the following error:
```bash
Run /tmp/test/.venv/bin/python main.py test
Traceback (most recent call last):
  File "/home/pi/actions-runner/_work/sss/sss/main.py", line 3, in <module>
    from runners import simulator, kiosk, demo, test, utils
  File "/home/pi/actions-runner/_work/sss/sss/runners/simulator.py", line [7](https://github.com/NET-BYU/sss/runs/7138415273?check_suite_focus=true#step:6:8), in <module>
    import pygame
  File "/tmp/test/.venv/lib/python3.9/site-packages/pygame/__init__.py", line [8](https://github.com/NET-BYU/sss/runs/7138415273?check_suite_focus=true#step:6:9)3, in <module>
    from pygame.base import *  # pylint: disable=wildcard-import; lgtm[py/polluting-import]
ImportError: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

**Review by apal6981 — CHANGES_REQUESTED** [review]
See @christopolise request

**Review by christopolise — APPROVED** [review]
Looks great!

**Comment by philipbl** [comment]
I fixed the problem.

**Review by apal6981 — APPROVED** [review]

**Pull request merged**
