### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by christopolise**
Just a quick landing page for the repo. Can't believe we didn't have a README before :man_facepalming: . If there is anything else that you think should be added, let me know.

### CODE REVIEW

**Review by apal6981 — CHANGES_REQUESTED** [review]
Even though everything is in the docs. I would bold the statement that these commands can only be run after everything else is installed. Make it obvious they need to go to the docs.

**Review by schielb — APPROVED** [review]
Great idea! Leave the branch alive, we can go through and add more detail later on.

**Review by apal6981 — APPROVED** [review]
thanks

**Comment by schielb** [comment]
Woohoo!

**Pull request merged**
