### PR TITLE
Snake fix

### PR DESCRIPTION
**Pull request by apal6981**
Snake
- updated controls back to up left right down
- User can't turn back themselves as they used to be able to

Snake AI
- hopefully fixed speed of the snake
- temp fix to screen pausing while searching for food

Both
- cleaned all files with black
- got rid of most pylint errors
- made starting snake length 3 instead of one to make original games
- changed logging statements from info level to debug

### CODE REVIEW

**Review by philipbl — APPROVED** [review]
Looks good! 🐍

**Review by christopolise — COMMENTED** [review]
Pylint adherence looks great! I will approve it as soon as I get it tested on hardware

**Review by christopolise — CHANGES_REQUESTED** [review]
Saw that the debugging output was taken out of the `snake` demo but still is printing in `snake_ai`. I think it is good to have it classified at the `debug` level so that we could perhaps suppress `debug` all together when writing to the logs.. @philipbl what do you think?

**Comment by philipbl** [comment]
@christopolise, I agree. I can make that an CLI option for the runners. I will add a `-v` flag.

**Review by christopolise — APPROVED** [review]

**Comment by christopolise** [comment]
Awesome. So @apal6981 you are probably good to have those debug statements wherever you like going forward. I'mma merge now

**Pull request merged**
